Repository makerdao/community, pull requests merged in 2019-06, with the labels that each got.

#113 cut it down, removed some unnecessary text and words.
  meetups/README.md
Labels: portal

#120 added Episode 41 G&R Meeting Summary
  SUMMARY.md
Labels: governance

#126 Add first version of Governance and Risk Meeting: Ep. 41 transcription
  SUMMARY.md
  governance/governance-and-risk-meetings/transcripts/episode-39.md
  governance/governance-and-risk-meetings/transcripts/episode-40.md
  governance/governance-and-risk-meetings/transcripts/episode-41.md
Labels: transcripts
