Repository makerdao/community, pull requests merged in 2020-10, with the labels that each got.

#849 Polls in ES
  governance/es/polls/Adoptar Enfoque Flexible Transparente Incorporacion Colateral - 10:05:2020.md
  governance/es/polls/Añadir Tipo de Vault ETH-B - 10:05:2020.md
  governance/es/polls/Base Rate Adjustment - 10:05:2020.md
Labels: automerge

#867 Legacy Redirects B: Added redirects based on excel sheet
  content/en/contribute/index.mdx
  content/en/contributing/cdip-contributor-highlights.jpg
  content/en/contributing/cdip-explainer.md
  content/en/contributing/contributor-onboarding-guide.md
  content/en/contributing/contributor-tools-guide.md
  content/en/contributing/earn-as-a-contributor.md
  content/en/contributing/educational-reference-documentation-process.jpg
  content/en/contributing/faq.md
  content/en/contributing/github-fixing-a-commit.png
  content/en/contributing/gnr-summary-guide.md
  content/en/contributing/gnr-summary-template.md
  content/en/contributing/hackmd-markdown-download.png
  content/en/contributing/index.md
  content/en/contributing/repository-url.png
  content/en/contributing/reviewer-guide.md
  content/en/contributing/visual-style-guide.md
  content/en/contributing/writing-style-guide.md
  content/en/governance/common-topics.md
  content/en/governance/core-principles.md
  content/en/governance/executive-audit.md
  content/en/governance/governance-tools.md
  content/en/governance/index.md
  content/en/governance/meeting-schedule.md
  content/en/grants/audits/CDP Insurance - Audit.pdf
  content/en/grants/audits/CHAI - Audit.pdf
  content/en/grants/audits/Degens - Audit.pdf
  content/en/grants/audits/LimePay - Audit.pdf
  content/en/grants/audits/PoolTogether - Audit.pdf
  content/en/grants/audits/StablePay - Audit.pdf
  content/en/grants/grantee-playbook.md
  content/en/grants/index.md
  content/en/hackathons/developer-quick-start-guide.md
  content/en/hackathons/faq.md
  content/en/hackathons/index.md
  content/en/hackathons/organizer-quick-start-guide.md
  content/en/hackathons/requirements.md
  content/en/hackathons/winners.md
  content/en/meetups/budget-guide.md
  content/en/meetups/event-formats-guide.md
  content/en/meetups/faq.md
  content/en/meetups/getting-started-guide.md
  content/en/meetups/index.md
  content/en/meetups/meetup-diy-kit-es.md
  content/en/meetups/promotion-guide.md
  content/en/meetups/requesting-funds.md
  content/en/onboarding/index.md
  content/en/onboarding/vault-onboarding.md
  content/en/onboarding/voter-onboarding.md
  content/en/test.mdx
  gatsby-config.js
  gatsby-node.js
Labels: automerge

#865 Governance Polls 2020-10-12
  governance/polls/Base Rate Adjustment - October 12, 2020.md
  governance/polls/Inclusion Poll - MIP13c3-SP3 - 12 October, 2020.md
  governance/polls/Inclusion Poll - MIP13c3-SP4 - 12 October, 2020.md
  governance/polls/Inclusion Poll - MIP13c3-SP5 - 12 October, 2020.md
  governance/polls/Inclusion Poll - MIP14 - 12 October, 2020.md
  governance/polls/Inclusion Poll - MIP20 - 12 October, 2020.md
  governance/polls/Inclusion Poll - MIP21 - 12 October, 2020.md
  governance/polls/Inclusion Poll - MIP22 - 12 October, 2020.md
  governance/polls/Inclusion Poll - MIP23 - 12 October, 2020.md
  governance/polls/Proposal - Add BAL as a Collateral Type - October 12, 2020.md
  governance/polls/Proposal - Add YFI as a Collateral Type - October 12, 2020.md
  governance/polls/Proposal - Rates V2 Poll - October 12, 2020.md
Labels: governance

#870 Tb FAQS and 404 issues
  content/en/404.mdx
  content/en/faqs/dai.md
  content/en/faqs/dsr.md
  content/en/faqs/emergency-shutdown.md
  content/en/faqs/glossary.md
  content/en/faqs/governance.md
  content/en/faqs/index.md
  content/en/faqs/liquidation.md
  content/en/faqs/makerdao.md
  content/en/faqs/mkr-token.md
  content/en/faqs/oracles.md
  content/en/faqs/stability-fee.md
  content/en/faqs/vault.md
  content/en/learn/Dai/dsr.mdx
  content/en/learn/governance/emergency-shutdown.mdx
  src/pages/404.js
Labels: automerge

#879 Spanish Polls from 12.10.2020
  governance/es/polls/10122020EncuestaAjustedeTasa Base.md
  governance/es/polls/10122020EncuestaAnadirBALcomoTipodeColateral.md
  governance/es/polls/10122020EncuestaAnadirYFIcomoTipodeColateral.md
  governance/es/polls/10122020EncuestaEncuestadeTasasV2.md
  governance/es/polls/10122020EncuestadeInclusionparaActivosdelMundoRealPrestadorResp.md
  governance/es/polls/10122020EncuestadeInclusionparaDeclaraciondeIntencionesFondodeR.md
  governance/es/polls/10122020EncuestadeInclusionparaDeclaraciondeIntencionesMakertra.md
  governance/es/polls/10122020EncuestadeInclusionparaDeclaraciondeIntenciones_Prestad.md
  governance/es/polls/10122020EncuestadeInclusionparaRolesyEstructuradeDominio.md
  governance/es/polls/10122020EncuestadeInclusionparaelModulodeAjustedePreciosObjetivo.md
  governance/es/polls/10122020EncuestadeInclusionparaelModulodeLiquidacionDirectadeCentrifuge.md
  governance/es/polls/10122020EncuestadeInclusionparalaTransferenciadeDAIdelProtocolo.md
Labels: automerge

#876 Gnr111and112 + Meetup Funding Page PR from last week
  SUMMARY.md
  content/en/funding/meetup-funding.mdx
  governance/governance-and-risk-meetings/summaries/README.md
  governance/governance-and-risk-meetings/summaries/episode-111.md
  governance/governance-and-risk-meetings/summaries/episode-112.md
Labels: automerge, governance, meetups

#878 Tb fix/makerdaopagesfix
  content/en/404.mdx
  content/en/learn/MakerDAO/index.mdx
  governance/es/polls/Adoptar Enfoque Flexible Transparente Incorporacion Colateral - 10-05-2020.md
  governance/es/polls/Añadir Tipo de Vault ETH-B - 10-05-2020.md
  governance/es/polls/Base Rate Adjustment - 10-05-2020.md
  governance/polls/Base Rate Adjustment - October 12, 2020.md
  governance/polls/Inclusion Poll - MIP13c3-SP3 - October 12, 2020.md
  governance/polls/Inclusion Poll - MIP13c3-SP4 - October 12, 2020.md
  governance/polls/Inclusion Poll - MIP13c3-SP5 - October 12, 2020.md
  governance/polls/Inclusion Poll - MIP14 - October 12, 2020.md
  governance/polls/Inclusion Poll - MIP20 - October 12, 2020.md
  governance/polls/Inclusion Poll - MIP21 - October 12, 2020.md
  governance/polls/Inclusion Poll - MIP22 - October 12, 2020.md
  governance/polls/Inclusion Poll - MIP23 - October 12, 2020.md
  governance/polls/Proposal - Add BAL as a Collateral Type - October 12, 2020.md
  governance/polls/Proposal - Add YFI as a Collateral Type - October 12, 2020.md
  governance/polls/Proposal - Rates V2 Poll - October 12, 2020.md
  governance/polls/templates/Proposal - Add $asset_code as a Collateral Type - $date_MONTH_DD,_YYYY.md
  src/modules/layouts/site_layout.js
Labels: automerge

#880 R2d to prod
  SUMMARY.md
  content/en/404.mdx
  content/en/funding/meetup-funding.mdx
  content/en/learn/MakerDAO/index.mdx
  governance/es/polls/Adoptar Enfoque Flexible Transparente Incorporacion Colateral - 10-05-2020.md
  governance/es/polls/Añadir Tipo de Vault ETH-B - 10-05-2020.md
  governance/es/polls/Base Rate Adjustment - 10-05-2020.md
  governance/governance-and-risk-meetings/summaries/README.md
  governance/governance-and-risk-meetings/summaries/episode-111.md
  governance/governance-and-risk-meetings/summaries/episode-112.md
  governance/polls/Base Rate Adjustment - October 12, 2020.md
  governance/polls/Inclusion Poll - MIP13c3-SP3 - October 12, 2020.md
  governance/polls/Inclusion Poll - MIP13c3-SP4 - October 12, 2020.md
  governance/polls/Inclusion Poll - MIP13c3-SP5 - October 12, 2020.md
  governance/polls/Inclusion Poll - MIP14 - October 12, 2020.md
  governance/polls/Inclusion Poll - MIP20 - October 12, 2020.md
  governance/polls/Inclusion Poll - MIP21 - October 12, 2020.md
  governance/polls/Inclusion Poll - MIP22 - October 12, 2020.md
  governance/polls/Inclusion Poll - MIP23 - October 12, 2020.md
  governance/polls/Proposal - Add BAL as a Collateral Type - October 12, 2020.md
  governance/polls/Proposal - Add YFI as a Collateral Type - October 12, 2020.md
  governance/polls/Proposal - Rates V2 Poll - October 12, 2020.md
  governance/polls/templates/Proposal - Add $asset_code as a Collateral Type - $date_MONTH_DD,_YYYY.md
  package.json
  src/modules/layouts/site_layout.js
  yarn.lock
Labels: automerge

#881 update 404 ...again
  content/en/404.mdx
Labels: automerge

#882 r2d 404 fix
  content/en/404.mdx
Labels: automerge

#883 3rd times a charm
  content/en/404.mdx
Labels: automerge

#884 Create MAM - 2020.10.06.md
  governance/mandated-actors-meetings/summaries/MAM - 2020.10.06.md
Labels: automerge

#886 Gnr 113 summary added to archive
  SUMMARY.md
  content/en/funding/meetup-funding.mdx
  governance/governance-and-risk-meetings/summaries/README.md
  governance/governance-and-risk-meetings/summaries/episode-111.md
  governance/governance-and-risk-meetings/summaries/episode-112.md
  governance/governance-and-risk-meetings/summaries/episode-113.md
Labels: automerge, governance

#899 Tb redirects
  gatsby-node.js
Labels: automerge

#900 Polls 19Oct20
  governance/es/polls/Approve Maker Representatives - October 19, 2020.md
  governance/es/polls/Community Greenlight Poll - UNI (Uniswap) - October 19, 2020.md
  governance/es/polls/Community Greenlight Poll - yUSD (yyCRV) - October 19, 2020.md
  governance/es/polls/Community_Greenlight_Poll_CRO_Crypto_com_Coin_October_19,_2020.md
  governance/es/polls/Community_Greenlight_Poll_CRV_Curve_DAO_Token_October_19,_2020.md
  governance/es/polls/Community_Greenlight_Poll_KF_DROP_Kickfurther_DROP_October_19,_2020.md
  governance/es/polls/Community_Greenlight_Poll_OMG_OMG_Network_October_19,_2020.md
  governance/es/polls/Community_Greenlight_Poll_OST_1_UPRETS_Oosten_Fund_I_LP_October.md
  governance/es/polls/Community_Greenlight_Poll_UNI_V2_USDT_ETH_Uniswap_USDT_WETH_Liquidity.md
  governance/es/polls/Community_Greenlight_Poll_UNI_V2_WBTC_ETH_Uniswap_WBTC_WETH_Liquidity.md
  governance/es/polls/Community_Greenlight_Poll_aUSDC_Aave_USDC_October_19,_2020.md
  governance/es/polls/Community_Greenlight_Poll_cUSDC_Compound_USDC_cToken_October_19.md
  governance/es/polls/Increase the Surplus Auction Buffer - October 19, 2020.md
  governance/es/polls/Monthly MIPs Governance Poll - October 19, 2020.md
  governance/es/polls/Whitelist_B_Protocol_on_ETHUSD_Medianizer_Oracle_MIP10c9_SP12_October.md
  governance/es/polls/Whitelist_B_Protocol_on_ETHUSD_Oracle_Security_Module_MIP10c9_SP13.md
Labels: automerge

#914 Production push
  gatsby-node.js
  package.json
  yarn.lock
Labels: automerge

#906 Update issue templates- CDIP
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/create-a-cdip.md
  .github/ISSUE_TEMPLATE/create-a-new-task.md
Labels: automerge

#912 Archiving GnR summary for ep 114
  content/en/learn/governance/governance-faq.md
  content/en/learn/governance/participate.mdx
  gatsby-node.js
  governance/governance-and-risk-meetings/summaries/README.md
  governance/governance-and-risk-meetings/summaries/episode-114.md
  package.json
  yarn.lock
Labels: automerge

#922 keeping master and r2d in sync
  governance/governance-and-risk-meetings/summaries/README.md
  governance/governance-and-risk-meetings/summaries/episode-114.md
  governance/polls/Proposal - Add GUSD as a Collateral Type - October 26, 2020.md
  governance/polls/Proposal - Add PAXG as a Collateral Type - October 26, 2020.md
  governance/polls/templates/Adjust the $ilk_name Risk Premium -  $date_MONTH_DD,_YYYY.md
  governance/polls/templates/Base Rate Adjustment - $date_MONTH_DD,_YYYY.md
  governance/polls/templates/Dai Savings Rate Spread Adjustment - $date_MONTH_DD,_YYYY.md
  governance/polls/templates/Debt Ceiling Adjustment for $ilk_name - $date_MONTH_DD,_YYYY.md
  governance/polls/templates/Inclusion Poll - $mip_code - $date_MONTH_DD,_YYYY.md
  governance/polls/templates/Increase Surplus Auction Buffer - $date_MONTH_DD,_YYYY.md
  governance/polls/templates/MIP10c9-SP# - Whitelist $whitelisted_entity on $whitelisted_oracle Oracle -  $date_MONTH_DD,_YYYY.md
  governance/polls/templates/MIP9 Community Greenlight Poll - $asset_name - $date_MONTH_DD,_YYYY.md
  governance/polls/templates/MIPs Monthly Governance Poll -  $date_MONTH_DD,_YYYY.md
  governance/polls/templates/Proposal - Add $asset_code as a Collateral Type - $date_MONTH_DD,_YYYY.md
  governance/votes/Executive vote - October 23, 2020.md
  governance/votes/templates/Executive vote - $date_MONTH_DD,_YYYY.md
Labels: automerge

#929 MAM-notes-1013+1020
  governance/mandated-actors-meetings/summaries/MAM - 2020.10.13.md
  governance/mandated-actors-meetings/summaries/MAM - 2020.10.20.md
Labels: automerge
