Repository makerdao/community, pull requests merged in 2021-05, with the labels that each got.

#1306 Blog and Edits
  blogPosts/en/blog/community/Engineering-for-communities.mdx
  blogPosts/en/blog/community/eng-language.mdx
  blogPosts/en/blog/community/eng-navigation.mdx
  blogPosts/en/blog/community/eng-search.mdx
  blogPosts/en/blog/community/stablecoins.mdx
  blogPosts/en/blog/editorial/Glossary-Addition.mdx
  blogPosts/en/blog/editorial/Top-Sources-Maker-Governance.mdx
  blogPosts/en/blog/governance/Maker-Governance-Review-March-2021.mdx
  content/all-contributors.json
Labels: automerge

#1328 Add Gnr139 Meeting Minutes to Blog
  blogPosts/en/blog/meeting-minutes/Gnr-138.mdx
  blogPosts/en/blog/meeting-minutes/Gnr-139.mdx
Labels: automerge, blog

#1310 small change to Sai Teja Author credentials
  .all-contributorsrc
Labels: automerge, editing

#1330 Add April Governance Review Blog
  blogPosts/en/blog/governance/Maker-Governance-Review-April-2021.mdx
  static/images/blog_headers/monthlygov_apr21.png
  static/images/mipscalmay21.png
Labels: automerge, blog

#1331 fixing build error on strings in description
  blogPosts/en/blog/community/eng-language.mdx
Labels: automerge

#1332 Updating address for autoexec.sol
  blogPosts/en/blog/meeting-minutes/Gnr-138.mdx
  blogPosts/en/blog/meeting-minutes/Gnr-139.mdx
  content/all-contributors.json
  content/en/learn/governance/module-dciam.md
  flow-typed/__generated__/gatsby-types.flow.js
  src/molecules/Footer/Footer.js
Labels: automerge

#1333 Merging edits
  blogPosts/en/blog/meeting-minutes/Gnr-138.mdx
  blogPosts/en/blog/meeting-minutes/Gnr-139.mdx
  content/all-contributors.json
  content/en/learn/governance/module-dciam.md
  flow-typed/__generated__/gatsby-types.flow.js
  src/molecules/Footer/Footer.js
Labels: automerge

#1325 2021-05 Parameter Changes Proposal of MakerDAO Open Market Committee
  governance/polls/Parameter Changes Proposal - PPG-OMC-001 - May 10, 2021.md
Labels: automerge

#1342 greenlight polls for 2021-05 MIP9 - SLP
  governance/polls/MIP 9 Community Greenlight Poll - SLP-AAVE-ETH - May 17, 2021.md
  governance/polls/MIP 9 Community Greenlight Poll - SLP-COMP-ETH - May 17, 2021.md
  governance/polls/MIP 9 Community Greenlight Poll - SLP-ETH-USDT - May 17, 2021.md
  governance/polls/MIP 9 Community Greenlight Poll - SLP-LINK-ETH - May 17, 2021.md
  governance/polls/MIP 9 Community Greenlight Poll - SLP-SNX-ETH - May 17, 2021.md
  governance/polls/MIP 9 Community Greenlight Poll - SLP-SUSHI-ETH - May 17, 2021.md
  governance/polls/MIP 9 Community Greenlight Poll - SLP-UNI-ETH - May 17, 2021.md
  governance/polls/MIP 9 Community Greenlight Poll - SLP-USDC-ETH - May 17, 2021.md
  governance/polls/MIP 9 Community Greenlight Poll - SLP-WBTC-ETH - May 17, 2021.md
  governance/polls/MIP 9 Community Greenlight Poll - SLP-YFI-ETH - May 17, 2021.md
Labels: automerge
